// PRZYBORNIK POCZĄTEK
        document.querySelectorAll('.KOZLOWSKISEBASTIAN_PRZYBORNIK-PRZYCISK').forEach(btn => {
            btn.onclick = () => {
                const polish = {'Ą':'A','Ć':'C','Ę':'E','Ł':'L','Ń':'N','Ó':'O','Ś':'S','Ź':'Z','Ż':'Z','ą':'a','ć':'c','ę':'e','ł':'l','ń':'n','ó':'o','ś':'s','ź':'z','ż':'z'};
                const path = btn.innerText.toUpperCase().replace(/[ĄĆĘŁŃÓŚŹŻąćęłńóśźż]/g, m => polish[m]).replace(/ /g, '-');
            location.href = `https://kozlowskisebastian.pl/${path}/`;
            };
        });
// PRZYBORNIK KONIEC
// LICZYDŁO POCZĄTEK
        document.addEventListener('DOMContentLoaded', () => {
            const KOZLOWSKISEBASTIAN_LICZYDLO_JEDNOSTKA = document.getElementById('KOZLOWSKISEBASTIAN_LICZYDLO-JEDNOSTKA');
            const KOZLOWSKISEBASTIAN_LICZYDLO_ILOSC = document.getElementById('KOZLOWSKISEBASTIAN_LICZYDLO-ILOSC');
            const KOZLOWSKISEBASTIAN_LICZYDLO_KILOMETRY = document.getElementById('KOZLOWSKISEBASTIAN_LICZYDLO-KILOMETRY');
            const KOZLOWSKISEBASTIAN_LICZYDLO_PRZYCISK = document.querySelector('.KOZLOWSKISEBASTIAN_LICZYDLO-PRZYCISK');
        KOZLOWSKISEBASTIAN_LICZYDLO_JEDNOSTKA.addEventListener('change', () => {
            const KOZLOWSKISEBASTIAN_LICZYDLO_POKAZ_KILOMETRY = ['PALIWO', 'TRASA'].includes(KOZLOWSKISEBASTIAN_LICZYDLO_JEDNOSTKA.value);
        KOZLOWSKISEBASTIAN_LICZYDLO_KILOMETRY.style.display = KOZLOWSKISEBASTIAN_LICZYDLO_POKAZ_KILOMETRY ? 'block' : 'none';
        KOZLOWSKISEBASTIAN_LICZYDLO_ILOSC.placeholder = KOZLOWSKISEBASTIAN_LICZYDLO_JEDNOSTKA.value === 'TRASA' ? 'ŚREDNIE SPALANIE' : 'ILOŚĆ';
        });
        KOZLOWSKISEBASTIAN_LICZYDLO_PRZYCISK.addEventListener('click', () => {
            const KOZLOWSKISEBASTIAN_LICZYDLO_CENA = parseFloat(document.getElementById('KOZLOWSKISEBASTIAN_LICZYDLO-CENA').value);
            const KOZLOWSKISEBASTIAN_LICZYDLO_ILOSC_WARTOSC = parseFloat(KOZLOWSKISEBASTIAN_LICZYDLO_ILOSC.value);
            const KOZLOWSKISEBASTIAN_LICZYDLO_JEDNOSTKA_WARTOSC = KOZLOWSKISEBASTIAN_LICZYDLO_JEDNOSTKA.value;
            const KOZLOWSKISEBASTIAN_LICZYDLO_KILOMETRY_WARTOSC = parseFloat(KOZLOWSKISEBASTIAN_LICZYDLO_KILOMETRY.value);
            const KOZLOWSKISEBASTIAN_LICZYDLO_WYNIK = document.getElementById('KOZLOWSKISEBASTIAN_LICZYDLO-WYNIK');
                if (!KOZLOWSKISEBASTIAN_LICZYDLO_CENA || !KOZLOWSKISEBASTIAN_LICZYDLO_ILOSC_WARTOSC) {
            KOZLOWSKISEBASTIAN_LICZYDLO_WYNIK.innerHTML = "Wprowadź wymagane wartości!";
            return;
            }
            const KOZLOWSKISEBASTIAN_LICZYDLO_OBLICZENIA = {
                ML: () => `Cena za litr: ${(KOZLOWSKISEBASTIAN_LICZYDLO_CENA / KOZLOWSKISEBASTIAN_LICZYDLO_ILOSC_WARTOSC * 1000).toFixed(2)} zł`,
                DAG: () => `Cena za kg: ${(KOZLOWSKISEBASTIAN_LICZYDLO_CENA / KOZLOWSKISEBASTIAN_LICZYDLO_ILOSC_WARTOSC * 100).toFixed(2)} zł`,
                PALIWO: () => {
                if (!KOZLOWSKISEBASTIAN_LICZYDLO_KILOMETRY_WARTOSC) return "Wprowadź przejechane kilometry!";
            const KOZLOWSKISEBASTIAN_LICZYDLO_SPALANIE = (KOZLOWSKISEBASTIAN_LICZYDLO_ILOSC_WARTOSC / KOZLOWSKISEBASTIAN_LICZYDLO_KILOMETRY_WARTOSC) * 100;
            const KOZLOWSKISEBASTIAN_LICZYDLO_CALKOWITY_KOSZT = KOZLOWSKISEBASTIAN_LICZYDLO_CENA * KOZLOWSKISEBASTIAN_LICZYDLO_ILOSC_WARTOSC;
            const KOZLOWSKISEBASTIAN_LICZYDLO_KOSZT_NA_KM = KOZLOWSKISEBASTIAN_LICZYDLO_CALKOWITY_KOSZT / KOZLOWSKISEBASTIAN_LICZYDLO_KILOMETRY_WARTOSC;
            return `Spalanie: ${KOZLOWSKISEBASTIAN_LICZYDLO_SPALANIE.toFixed(2)} l/100km<br>Koszt na 100km: ${(KOZLOWSKISEBASTIAN_LICZYDLO_KOSZT_NA_KM * 100).toFixed(2)} zł<br>Koszt za 1km: ${KOZLOWSKISEBASTIAN_LICZYDLO_KOSZT_NA_KM.toFixed(4)} zł<br>Całkowity koszt: ${KOZLOWSKISEBASTIAN_LICZYDLO_CALKOWITY_KOSZT.toFixed(2)} zł (dla ${KOZLOWSKISEBASTIAN_LICZYDLO_KILOMETRY_WARTOSC} km)`;
            },
                TRASA: () => {
                if (!KOZLOWSKISEBASTIAN_LICZYDLO_KILOMETRY_WARTOSC) return "Wprowadź dystans!";
            const KOZLOWSKISEBASTIAN_LICZYDLO_CALKOWITE_PALIWO = (KOZLOWSKISEBASTIAN_LICZYDLO_KILOMETRY_WARTOSC * KOZLOWSKISEBASTIAN_LICZYDLO_ILOSC_WARTOSC) / 100;
            const KOZLOWSKISEBASTIAN_LICZYDLO_CALKOWITY_KOSZT = KOZLOWSKISEBASTIAN_LICZYDLO_CALKOWITE_PALIWO * KOZLOWSKISEBASTIAN_LICZYDLO_CENA;
            const KOZLOWSKISEBASTIAN_LICZYDLO_KOSZT_NA_KM = KOZLOWSKISEBASTIAN_LICZYDLO_CALKOWITY_KOSZT / KOZLOWSKISEBASTIAN_LICZYDLO_KILOMETRY_WARTOSC;
            return `Koszt trasy (${KOZLOWSKISEBASTIAN_LICZYDLO_KILOMETRY_WARTOSC} km): ${KOZLOWSKISEBASTIAN_LICZYDLO_CALKOWITY_KOSZT.toFixed(2)} zł<br>Zużycie paliwa: ${KOZLOWSKISEBASTIAN_LICZYDLO_CALKOWITE_PALIWO.toFixed(2)} l<br>Koszt na 100km: ${(KOZLOWSKISEBASTIAN_LICZYDLO_KOSZT_NA_KM * 100).toFixed(2)} zł<br>Koszt za 1km: ${KOZLOWSKISEBASTIAN_LICZYDLO_KOSZT_NA_KM.toFixed(4)} zł`;
            }
        };
        KOZLOWSKISEBASTIAN_LICZYDLO_WYNIK.innerHTML = KOZLOWSKISEBASTIAN_LICZYDLO_OBLICZENIA[KOZLOWSKISEBASTIAN_LICZYDLO_JEDNOSTKA_WARTOSC]();
        });
        KOZLOWSKISEBASTIAN_LICZYDLO_KILOMETRY.style.display = 'none';
});
// LICZYDŁO KONIEC
